image: nixos/unstable
secrets:
  - 63b447f7-4014-430a-b42c-455950b2a07c
  - 6f5a2956-4336-4049-934a-eaaa6feec964
packages:
  - nixos.go
  - nixos.hut
  - nixos.golangci-lint
tasks:
  - tests: |
      pushd emailer
      go test -mod=vendor -v ./...
      popd
  - lint: |
      pushd emailer
      golangci-lint run
      popd
  - build: |
      pushd emailer
      go build -mod=vendor ./cmd/...
      ./emailer -h
      popd
  - artifacts: |
      pushd emailer
      GOOS=linux go build -mod=vendor ./cmd/...
      GOOS=windows go build -mod=vendor ./cmd/...
      GOOS=darwin go build -mod=vendor -o emailer.darwin ./cmd/...
      hut --config ~/.hut_config git artifact upload emailer emailer.exe emailer.darwin
      popd
