image: nixos/unstable
secrets:
  - 63b447f7-4014-430a-b42c-455950b2a07c
packages:
  - nixos.go
tasks:
  - tests: |
      pushd emailer
      go test ./...
      popd
  - build: |
      pushd emailer
      go build ./cmd/...
      ./emailer -h
      popd
